# Github Actions Deployment
# Updated code is pushed to github repo and docker image is built + pushed to docker hub
# Kubernetes-repo is updated to reflect latest kubernetes manifest deployment
# ArgoCD monitors and automatically synchronizes K8s live-state to ensure deployment

name: Build and Deploy Aviale to Kubernetes with ArgoCD

on:
  push:
    branches:
      - main  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Aviale repo
      - name: Checkout Aviale app repo
        uses: actions/checkout@v2

      # Docker Build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker Image
      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t rahimhussain95/aviale:$IMAGE_TAG .
          docker push rahimhussain95/aviale:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
      # Github Actions securely access kubernetes-repo
      - name: Checkout Kubernetes repo
        uses: actions/checkout@v2
        with:
          repository: rahimhussain95/kubernetes-repo 
          token: ${{ secrets.KUBERNETES_REPO_TOKEN }}
          path: kubernetes-repo
      
      # Kubernetes deploys updated container
      - name: Update Kubernetes deployment manifest
        run: |
          cd kubernetes-repo
          sed -i 's|image: rahimhussain95/aviale:.*|image: rahimhussain95/aviale:${{ env.IMAGE_TAG }}|' apps/aviale/deployment.yaml
          git config --global user.email "rahimh.dev@gmail.com"
          git config --global user.name "GitHub Actions"
          git add apps/aviale/deployment.yaml
          git commit -am "Update deployment image to rahimhussain95/aviale:${{ env.IMAGE_TAG }}"
          git push origin main

      ## Allows for ArgoCD to manually sync and deploy. Synchronization is set to auto-sync. Toggle + configure to set manual deployment.
      # - name: Notify ArgoCD to sync and deploy the updated app
      #   run: |
      #     curl -X POST https://argocd.home/api/v1/applications/aviale/sync \
      #       -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
      #       -H "Content-Type: application/json" \
      #       -d '{}'
